version: '3'

services:
  db1:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_HOST=pdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_NAME=users
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
