version: '3'

services:
  db1:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "alembic revision --autogenerate -m "commit" && alembic upgrade head && python main.py"
    volumes:
      - .:/src
    ports:
      - "8000:8089"
    depends_on:
      - db1
