"""commit

Revision ID: 26dc7a6321ca
Revises: 0d151a9900b4
Create Date: 2022-02-14 15:26:38.878480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dc7a6321ca'
down_revision = '0d151a9900b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
